### ISSUE TITLE
Create API to watermark visualizations

### ISSUE THREAD

**Issue by reynoldtan** [tripal/tripald3#10]

**Comment by laceysanderson** [comment]
Simply call the function tripalD3.placeWatermark() after tripalD3.drawFigure() call.

Example:
```
tripalD3.drawFigure(chartdata, {chart parameters});
tripalD3.placeWatermark();
```

By default, this method will stamp the image set in the css/watermark.png directory. This can be replaced with the ideal image for a unified watermark.

To customize watermark for chart in one page to a diagram in another page, provide a path to a watermark image to the function.

Example:
```
tripalD3.drawFigure(chartdata, {chart parameters});
tripalD3.placeWatermark({'watermark' : 'http://mysite.ca/images/logotype.png'});
```

**Comment by laceysanderson** [comment]
This issue will remain open until the above documentation is added to our readthedocs. @reynoldtan can you add this information please? It should be it's own page under `docs/dev_guide` and a separate page should be added at `docs/api`.

**Comment by laceysanderson** [comment]
Documentation added to the API
