### ISSUE TITLE
Example charts

### ISSUE THREAD

**Issue by felipead6** [tripal/tripald3#15]
Could anyone provide an example on how to use tripal3d to make eg bar chart?

**Comment by laceysanderson** [comment]
**Sorry for the delayed response! I've been away on leave and unable to answer until now.**

Here is the developer documentation with examples of creating the various charts: https://tripal-d3js-api.readthedocs.io/en/latest/dev_guide/draw_simplepie.html. However, I see that the simple bar chart is missing here 🤔 There are also examples in this code (I've highlighted the bar chart here): https://github.com/tripal/tripald3/blob/7.x-1.x/templates/tripald3_demo_page.tpl.php#L273-L320
